### ISSUE TITLE
请教 , Mac下导入的路径是什么

### ISSUE THREAD

**Issue by fanlb** [kairyou/SublimeInsertDatetime#2]

**Comment by kairyou** [comment]
你意思是如何安装吗?
菜单: `Preferences / Browse Packages` 就打开Packages目录了, 然后建立`SublimeInsertDatetime`目录.
也可以在terminal, 执行这个命令, 打开Packages目录: `open "/Users/$(whoami)/Library/Application Support/Sublime Text 3/Packages/"`

最终本插件目录就是 `"/Users/$(whoami)/Library/Application Support/Sublime Text 3/Packages/SublimeInsertDatetime"`
